-- 380 mm HE Shell based on 127 mm HE for template with alterations. Source: 
declare_weapon({category = CAT_SHELLS, name = "127_Mk49_AAC_1", user_name = _("Mk 49 AAC 1"),
	AP_cap_caliber = 127,
	Da0 = 0.005,
	Dv0 = 0.1,
	Da1 = 0.005,
	-- aiming_table = { {
			-- init_vel = 792
		-- },
		-- precalculateAimingTable = true,
		-- precalculateAirDefenceAimingTable = true
	-- },
	caliber = 127,
	cartridge = 0,
	cartridge_mass = 0,
	category = 7,
	charTime = 0,
	cumulative_mass = 0,
	cumulative_thickness = 0,
	cx = { 0.5, 0.43, 0.7, 0.138, 1.43 },
	damage_factor = 639,
	display_name = "Mk 49 AAC",
	explosive = 3.29,
	full_scale_time = -1,
	j = 0,
	k1 = 1.2e-09,
	l = 0,
	life_time = 10,
	mass = 25,
	model_name = "pula",
	payload = 0.40612885360901,
	piercing_mass = 25,

	rotation_freq = 7,
	round_mass = 25,
	s = 0,
	scale_tracer = 0,
	silent_self_destruction = false,
	smoke_tail_life_time = -1,
	subcalibre = false,
	tracer_off = 30,
	tracer_on = 0,
	type_name = "shell",
	user_name = "Mk 49 AAC",
	v0 = 792,
	visual_effect_correction = 0,
	visual_effect_correction_rebound = 0.1
})

declare_weapon({category = CAT_SHELLS, name = "127_Mk49_AAC_2", user_name = _("Mk 49 AAC 2"),
	AP_cap_caliber = 127,
	Da0 = 0.005,
	Dv0 = 0.1,
	Da1 = 0.005,
	-- aiming_table = { {
			-- init_vel = 792
		-- },
		-- precalculateAimingTable = true,
		-- precalculateAirDefenceAimingTable = true
	-- },
	caliber = 127,
	cartridge = 0,
	cartridge_mass = 0,
	category = 7,
	charTime = 0,
	cumulative_mass = 0,
	cumulative_thickness = 0,
	cx = { 0.5, 0.43, 0.7, 0.138, 1.43 },
	damage_factor = 639,
	display_name = "Mk 49 AAC",
	explosive = 3.29,
	full_scale_time = -1,
	j = 0,
	k1 = 1.2e-09,
	l = 0,
	life_time = 8,
	mass = 25,
	model_name = "pula",
	payload = 0.40612885360901,
	piercing_mass = 25,

	rotation_freq = 7,
	round_mass = 25,
	s = 0,
	scale_tracer = 0,
	silent_self_destruction = false,
	smoke_tail_life_time = -1,
	subcalibre = false,
	tracer_off = 30,
	tracer_on = 0,
	type_name = "shell",
	user_name = "Mk 49 AAC",
	v0 = 792,
	visual_effect_correction = 0,
	visual_effect_correction_rebound = 0.1
})

declare_weapon({category = CAT_SHELLS, name = "127_Mk49_HC_1", user_name = _("Mk 49 HC 1"),
	AP_cap_caliber = 127,
	Da0 = 0.005,
	Dv0 = 0.1,
	Da1 = 0.005,
	-- aiming_table = { {
			-- init_vel = 792
		-- },
		-- precalculateAimingTable = true,
		-- precalculateAirDefenceAimingTable = true
	-- },
	caliber = 127,
	cartridge = 0,
	cartridge_mass = 0,
	charTime = 0,
	cumulative_mass = 0,
	cumulative_thickness = 0,
	cx = { 0.5, 0.43, 0.7, 0.138, 1.43 },
	damage_factor = 639,
	display_name = "Mk 49 HC",
	explosive = 3.29,
	full_scale_time = -1,
	j = 0,
	k1 = 1.2e-09,
	l = 0,
	life_time = 6,
	mass = 25,
	model_name = "pula",
	payload = 0.40612885360901,
	piercing_mass = 25,

	rotation_freq = 7,
	round_mass = 25,
	s = 0,
	scale_tracer = 0,
	silent_self_destruction = false,
	smoke_tail_life_time = -1,
	subcalibre = false,
	tracer_off = 30,
	tracer_on = 0,
	type_name = "shell",
	user_name = "Mk 49 HC",
	v0 = 792,
	visual_effect_correction = 0,
	visual_effect_correction_rebound = 0.1
})

declare_weapon({category = CAT_SHELLS, name = "127_Mk49_HC_2", user_name = _("Mk 49 HC 2"),
	AP_cap_caliber = 127,
	Da0 = 0.005,
	Dv0 = 0.1,
	Da1 = 0.005,
	-- aiming_table = { {
			-- init_vel = 792
		-- },
		-- precalculateAimingTable = true,
		-- precalculateAirDefenceAimingTable = true
	-- },
	caliber = 127,
	cartridge = 0,
	cartridge_mass = 0,
	charTime = 0,
	cumulative_mass = 0,
	cumulative_thickness = 0,
	cx = { 0.5, 0.43, 0.7, 0.138, 1.43 },
	damage_factor = 639,
	display_name = "Mk 49 HC",
	explosive = 3.29,
	full_scale_time = -1,
	j = 0,
	k1 = 1.2e-09,
	l = 0,
	life_time = 4,
	mass = 25,
	model_name = "pula",
	payload = 0.40612885360901,
	piercing_mass = 25,

	rotation_freq = 7,
	round_mass = 25,
	s = 0,
	scale_tracer = 0,
	silent_self_destruction = false,
	smoke_tail_life_time = -1,
	subcalibre = false,
	tracer_off = 30,
	tracer_on = 0,
	type_name = "shell",
	user_name = "Mk 49 HC",
	v0 = 792,
	visual_effect_correction = 0,
	visual_effect_correction_rebound = 0.1
})

-- Kudos to currenthill, original Shell name is ModernUSNShips_127_AA
-- Download from https://currenthill.com/
-- note that some characteristics have been changed by TeTeT, see the old value as comment
declare_weapon({
	category 				= CAT_SHELLS,
	name 					= "vwv_mk12_127mm_AIR",
	user_name 				= _("127 mm AA"),
	model_name    			= "pula",
    projectile      		= "HE",
    payloadEffect   		= "Fragmentation",
    payloadMaterial 		= "RDX",
	v0						= 792, -- 1808.0,
	Dv0						= 0.001, -- 0.0002,
	Da0						= 0.0002, -- 0.00001,
	Da1						= 0.0001, -- 0.0,
	mass      				= 31.3,
	explosive     			= 31.3,
	life_time     			= 100,
	caliber     			= 127.0,
	s         				= 0.0,
	j         				= 0.0,
	l         				= 0.0,
	charTime    			= 0,
	cx        				= {0.0,0.52,0.67,0.14,1.76},
	k1        				= 7.6e-10,
	tracer_off    			= 100,
	scale_tracer  			= 1,
	scale_smoke    			= 12.0,
	smoke_opacity  			= 0.5,
	cartridge 				= 1,

	aiming_table			=
	{
		precalculateAirDefenceAimingTable = true,
		precalculateAimingTable = true,
		[1] = { init_vel = 1808.0 }
	}

});
